Remove removed revik, add FAMAS and GROZA in weapon vend
PMC-Unga-Marines/RuTGMC-Reborn pull request #129
Opened 2024-08-25 19:47 UTC by Tatarla

## `Основные изменения`
1. Убрал р-76 из вендора сла, фк и карго
2. Добавил фамас и грозу в вендор оружия
3. Добавил им ап и хп патроны и закинуть в вендор (в процессе)

## `Как это улучшит игру`
Никак

## `Ченджлог`
```
:cl:
add: Добавил Фамас и Грозу в вендор пушек
add: Добавил АП и ХП патроны Фамасу и Грозе
del: Удалил R-76
/:cl:
```

2024-08-25 20:02 UTC, Helg2 commented
Баффни р500 к уровню р76 тогда, а то при сравнении р500 проигрывает почти во всём

2024-08-26 18:17 UTC, homexp13 approved these changes

2024-08-26 19:31 UTC, Helg2 requested changes
Коробки с р76 всё еще попадаются в `/obj/item/loot_box/marine`

2024-08-27 14:58 UTC, homexp13 approved these changes
вроде нормально

2024-08-27 14:58 UTC, homexp13 reviewed
комментарий хелга только всё ещё в силе

2024-08-27 15:09 UTC, Helg2 commented on code/modules/projectiles/magazines/rifles.dm
> +	name = "\improper Type 71 magazine (7.62x39mm)"
```suggestion
	name = "\improper Type 71 AP magazine (7.62x39mm)"
```

2024-08-27 15:09 UTC, Helg2 commented on code/modules/projectiles/magazines/rifles.dm
> +	name = "\improper Type 71 magazine (7.62x39mm)"
```suggestion
	name = "\improper Type 71 HP magazine (7.62x39mm)"
```

2024-08-27 15:09 UTC, Helg2 approved these changes
Остальное вроде норм

2024-08-27 15:19 UTC, merged