Return of the tur, change in the status of modules and armor, new type of armor
PMC-Unga-Marines/RuTGMC-Reborn pull request #14
Opened 2024-07-14 14:54 UTC by Tatarla

## `Основные изменения`
1. Перебалансил статы модулей
2. Перебалансил статы брони
3. Изменил броню пилота - теперь она является уникальной. Имеет статы тяжелой, замедление средней. Это - заготовка на будущее(эта спецброня раундстартом для всех спецролей + в вендор за поинты)
4. Вернул тюр
5. Немного почистил код

## `Как это улучшит игру`
Изменяем статы по диздоку, добавляем разнообразие в игру

## `Ченджлог`
```
:cl:
```
balance: изменил баланс модулей
balance: изменил баланс брони
code: убрал вторичное наследование кода у брони пилота
code: вернул модуль тюра
/:cl:
```

2024-07-14 15:02 UTC, Helg2 commented on code/__DEFINES/loadout.dm
> +/* RUTGMC EDIT
?

2024-07-14 15:05 UTC, Helg2 commented on code/modules/clothing/modular_armor/xenonauten.dm
> -
Без `attachments_allowed = null` оно будет наследовать от родителя

2024-07-14 15:10 UTC, Tatarla commented on code/__DEFINES/loadout.dm
> +/* RUTGMC EDIT
Это перенос коммита, там дальше т2 модули в вендоре СЛа, что остались под модулем

2024-07-14 15:10 UTC, Tatarla commented on code/modules/clothing/modular_armor/xenonauten.dm
> -
Так и смысл в том, чтобы наследовало от родителя

2024-07-14 15:16 UTC, Helg2 commented on code/modules/clothing/modular_armor/xenonauten.dm
> -
Ладно

2024-07-16 10:13 UTC, Helg2 requested changes

2024-07-16 10:13 UTC, Helg2 commented on code/modules/clothing/modular_armor/attachments/modules.dm
>  	desc = "Designed for mounting on modular armor. A substantial amount of additional armor plating designed to grant the user extra protection against threats, ranging from xeno slashes to friendly fi
Поменяй описания у модулей, чтобы они соответствовали действительности.

2024-07-16 10:13 UTC, Helg2 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	desc = "Designed for mounting on a modular helmet. When attached, this system provides substantial resistance to most damaging hazards, ranging from xeno slashes to friendly fire incidents."
Тоже самое.

2024-07-16 10:13 UTC, Helg2 commented on code/modules/clothing/modular_armor/attachments/modules.dm
> +	soft_armor = list(MELEE = 5, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = -5, FIRE = 0, ACID = -5)
Тоже самое.

2024-07-16 10:13 UTC, Helg2 commented on code/modules/clothing/modular_armor/attachments/modules.dm
>  	desc = "Designed for mounting on a modular helmet. When attached, this system provides substantial resistance to most gunshot wounds by providing high internal padding within the helmet's structure.
Тоже самое.

2024-07-16 10:13 UTC, Helg2 commented on code/modules/clothing/modular_armor/attachments/modules.dm
>  	desc = "Designed for mounting on modular armor. This older model provides minor resistance to acid, biological, and radiological attacks. Pairing this with a Mimir helmet module and mask will make t
Тоже самое.

2024-07-16 16:06 UTC, Tatarla commented on code/modules/clothing/modular_armor/attachments/modules.dm
>  	desc = "Designed for mounting on modular armor. This older model provides minor resistance to acid, biological, and radiological attacks. Pairing this with a Mimir helmet module and mask will make t
За перевод приступлю в следующих ПРах

2024-07-17 15:21 UTC, Helg2 approved these changes
Хуй с тобой.

2024-07-17 15:24 UTC, Helg2 commented on code/__DEFINES/loadout.dm
> +/* RUTGMC EDIT
Только вспомнил, допиши коммент, чтобы не забыть что хотел сделать потом.

2024-07-18 06:20 UTC, merged