Some chems reb / fix
PMC-Unga-Marines/RuTGMC-Reborn pull request #153
Opened 2024-08-27 16:44 UTC by Tatarla

## `Основные изменения`
1. Бика, трико, пара, наниты теперь пурджат друг-друга
2. ОД бика и трико теперь дамажит токсинами

## `Как это улучшит игру`
Фикс отсутствия пурджа базовой химии
Теперь ОД бика и трико не перехиливается друг-другом, а наносит урон токсинами

2024-08-27 17:05 UTC, homexp13 commented on code/modules/reagents/reagents/medical.dm
> +		/datum/reagent/medicine/ifosfamide,
бикардин уже нанитами пуржиться
у ифосфамида гистамины всё пуржат,

2024-08-27 17:06 UTC, homexp13 commented on code/modules/reagents/reagents/medical.dm
> +		/datum/reagent/medicalnanites,
парацтамол уже пуржиться нанитами

2024-08-27 17:09 UTC, homexp13 commented on code/modules/reagents/reagents/medical.dm
> +		/datum/reagent/medicine/ifosfamide,
для кело тоже

2024-08-28 13:57 UTC, homexp13 requested changes
у тебя билд не компилится ты хоть в игру заходи дурачек

2024-08-28 14:56 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		Organrand.take_damage(1.0 * effect_str)
```suggestion
		Organrand.take_damage(1 * effect_str)
```

2024-08-28 15:07 UTC, Helg2 approved these changes
По коду норм

2024-08-28 15:13 UTC, homexp13 requested changes
наниты убирай из пурджа, они даже гипервеном не пурджаться

2024-08-28 15:36 UTC, homexp13 approved these changes

2024-08-28 15:46 UTC, merged