Llarge vehicle
PMC-Unga-Marines/RuTGMC-Reborn pull request #19
Opened 2024-07-16 08:35 UTC by homexp13

## `Основные изменения`

Добавляет танк и бтр, роли и тд

## `Как это улучшит игру`

ТАНКИ

## `Ченджлог`

```
:cl:
add: Портировал наземную технику с тгмц
/:cl:
```

2024-07-16 18:34 UTC, Helg2 commented
Какой пиздец

2024-07-17 15:47 UTC, fe-ed requested changes
Чини мувмент, слоняра

2024-07-18 05:07 UTC, Helg2 commented
Не забудь глянуть насколько сломается танк, при его броске с шаттла.

2024-07-18 14:47 UTC, fe-ed approved these changes

2024-07-19 07:45 UTC, Helg2 commented on _maps/map_files/debugdalus/tgs_debugdalus.dmm
> +/obj/item/weapon/sword/captain,
Мэх

2024-07-19 07:48 UTC, Helg2 commented on code/__DEFINES/jobs.dm
> +GLOBAL_LIST_INIT(jobs_engineering, list(CHIEF_SHIP_ENGINEER, SHIP_TECH))
?

2024-07-19 07:53 UTC, Helg2 commented on code/__DEFINES/traits.dm
> +
```suggestion
///Banished from the hive by the ruler
```

2024-07-19 07:57 UTC, Helg2 commented on code/_onclick/hud/screen_objects/screen_objects.dm
> +	icon_state = "pressure[human_mymob.pressure_alert]"
Они вроде бы всё также нигде не используются, наверное можно удалить повторно.

2024-07-19 08:01 UTC, Helg2 commented on code/datums/components/riding/riding_vehicle.dm
> +	//movable_parent.Move(next, direction, glide_size_override)
?

2024-07-19 08:05 UTC, Helg2 commented on code/datums/interior/interior_apc.dm
> +	icon_state = "apc_interior_29"
Добавь отступы

2024-07-19 08:06 UTC, Helg2 commented on code/datums/interior/interior_tank.dm
> +	icon_state = "tank_interior_22"
Тут тоже отступы

2024-07-19 08:07 UTC, Helg2 commented on code/datums/jobs/access.dm
> +			return list(ACCESS_MARINE_CAPTAIN, ACCESS_MARINE_COMMANDER, ACCESS_MARINE_LOGISTICS, ACCESS_MARINE_DROPSHIP, ACCESS_MARINE_PILOT, ACCESS_MARINE_MECH, ACCESS_MARINE_BRIDGE, ACCESS_MARINE_ARMORED)//
Возможно стоит добавить доступ к таду?

- [ ] 

- [ ]

2024-07-19 08:09 UTC, Helg2 commented on code/datums/jobs/job/shipside.dm
> +
Лишний отступ

2024-07-19 08:12 UTC, Helg2 commented on code/game/atoms/atom_appearance.dm
> +	var/list/managed_overlays
Перенеси в нормальное место

2024-07-19 08:20 UTC, Helg2 commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "marini_belt"
?

2024-07-19 08:36 UTC, homexp13 commented on code/__DEFINES/jobs.dm
> +GLOBAL_LIST_INIT(jobs_engineering, list(CHIEF_SHIP_ENGINEER, SHIP_TECH))
хм на офах так сделали, поменяю обратно

2024-07-19 08:38 UTC, homexp13 commented on code/datums/components/riding/riding_vehicle.dm
> +	//movable_parent.Move(next, direction, glide_size_override)
комментарий с офов, оставил на всякий

2024-07-19 08:41 UTC, homexp13 commented on code/game/atoms/atom_appearance.dm
> +	var/list/managed_overlays
так и должно быть, это рефактор с офов

2024-07-19 08:44 UTC, homexp13 commented on code/datums/jobs/access.dm
> +			return list(ACCESS_MARINE_CAPTAIN, ACCESS_MARINE_COMMANDER, ACCESS_MARINE_LOGISTICS, ACCESS_MARINE_DROPSHIP, ACCESS_MARINE_PILOT, ACCESS_MARINE_MECH, ACCESS_MARINE_BRIDGE, ACCESS_MARINE_ARMORED)//
убрал случайно, верну

2024-07-19 08:45 UTC, homexp13 commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "marini_belt"
это от рефактора с офов, щас починю

2024-07-19 08:48 UTC, homexp13 commented on code/datums/interior/interior_apc.dm
> +	icon_state = "apc_interior_29"
смерть...

2024-07-19 09:09 UTC, Helg2 commented on code/game/atoms/atom_appearance.dm
> +	var/list/managed_overlays
Кринж, но ладно

2024-07-19 16:19 UTC, Helg2 commented on code/modules/paperwork/paper.dm
> +
```suggestion
```

2024-07-19 16:27 UTC, Helg2 commented on code/modules/projectiles/projectile.dm
> -
?

2024-07-19 16:40 UTC, homexp13 commented on code/modules/projectiles/projectile.dm
> -
офы с рефактором убрали

2024-07-19 16:44 UTC, Helg2 approved these changes
Вроде норм

2024-07-20 07:13 UTC, Tatarla approved these changes

2024-07-20 07:13 UTC, merged