Some fix
PMC-Unga-Marines/RuTGMC-Reborn pull request #339
Opened 2024-09-15 19:32 UTC by Tatarla

## `Основные изменения`
1. Убрал двойной стул на Талосе
2. Лазпистолет теперь лезет в пистолетный пояс
3. Пофикшен спрайт у автоматического дробовика
4. Пофикшены магазины у фрилансеров

2024-09-15 19:35 UTC, homexp13 requested changes

2024-09-15 19:35 UTC, homexp13 commented on code/modules/clothing/modular_armor/attachments/chest_plates.dm
> -	slowdown = SLOWDOWN_ARMOR_VERY_HEAVY
cлоудаун у тяжёлой брони большой потому что у неё брони 55 а не 50 как раньше было, либо оставляй слоу либо уменьшай броню

2024-09-15 19:38 UTC, homexp13 commented on code/modules/projectiles/guns/energy.dm
> +	w_class = WEIGHT_CLASS_NORMAL
?

2024-09-16 12:26 UTC, Tatarla commented on code/modules/clothing/modular_armor/attachments/chest_plates.dm
> -	slowdown = SLOWDOWN_ARMOR_VERY_HEAVY
Это баланс так и задумано

2024-09-16 13:35 UTC, homexp13 approved these changes

2024-09-16 13:43 UTC, merged