Deletes a bunch of unused clothing.
PMC-Unga-Marines/RuTGMC-Reborn pull request #57
Opened 2024-07-30 13:06 UTC by Helg2

## `Основные изменения`
Удаляет много неиспользуемой одежды.
Те что использовались только на Дельте или в неиспользуемых шкафах я тоже немного удалил.

## `Как это улучшит игру`
Мы не Дрипстейшн, чтобы у нас было столько одежды.

## `Ченджлог`

```
:cl:
del: Удалил много старой одежды
/:cl:
```

2024-07-30 13:32 UTC, homexp13 commented on code/modules/clothing/head/head.dm
> -/obj/item/clothing/head/tgmcberet/hijab
АСУЖДАЮ МАКСИМАЛЬНО

2024-07-30 13:33 UTC, homexp13 commented on code/modules/clothing/masks/miscellaneous.dm
> -/obj/item/clothing/mask/pig
=(

2024-07-30 13:37 UTC, homexp13 commented
остальное по делу вроде

2024-07-30 13:39 UTC, homexp13 commented
а ну ещё dmi можно почистить если возможность есть

2024-07-30 13:47 UTC, Helg2 commented
> а ну ещё dmi можно почистить если возможность есть

Так лень

2024-07-30 15:23 UTC, Tatarla requested changes
Если чистить - то уж до конца, давай и дми

2024-08-01 07:00 UTC, Tatarla approved these changes
Ну если что, БЛЯТЬ - тоже спрайт

2024-08-01 14:41 UTC, merged