Adds a stomach organ, pills, food and etc go into stomach and only then to blood, refactors organs from datums to objects.
PMC-Unga-Marines/RuTGMC-Reborn pull request #69
Opened 2024-08-06 12:10 UTC by Helg2

## `Основные изменения`
Добавлен новый орган, желудок, если он надамажен то ты периодически блюёшь, а при попытке что-то съесть с шансом в `урон желудка * 3` ты блеванешь и получишь поинты инфекции в кол-ве `кол-во реагентов * 10`.
Съеденные реагенты, то есть таблетки, еда, вино, хлебание из реагент диспенсера, сначала направляются в желудок, где с помощью мозговыворачивающей формулы переводят реагенты уже в кровь.
Для анализатора здоровья добавлено соответственно отображение реагентов в желудке:
![image](https://github.com/user-attachments/assets/09792037-1c07-43ce-975f-fd5dbbfc9e1e)
Также переделан код органов, теперь это не датумы, а полноценные объекты, это было нужно чтобы приделать желудку реагенты. Но есть загвоздка в том что органы теперь также находятся в `contents` моба, и я не уверен насколько это хорошо или плохо.

## `Как это улучшит игру`
Я хуй знает.

## `Ченджлог`

```
:cl:
add: Съеденные реагенты теперь сначала идут в желудок, и уже потом из него в кровь.
refactor: Органы теперь не датумы.
/:cl:
```

2024-08-06 16:19 UTC, homexp13 requested changes
про датумы в дс написал

2024-08-07 13:04 UTC, homexp13 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	var/datum/internal_organ/heart/heart = new
тут вообще не понял, зачем создавать датум сердца если мы его вырезаем?

2024-08-07 13:04 UTC, homexp13 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		L?.get_damage(1, TRUE)
ну везде поменять

2024-08-07 13:43 UTC, Helg2 commented on code/game/objects/items/scanners.dm
> -			"dangerous" = reagent.overdosed || istype(reagent, /datum/reagent/toxin)
Токсины итак не отображаются, то есть эта строка бессмыслена

2024-08-07 13:48 UTC, Helg2 commented on code/modules/surgery/organs_internal.dm
> -	target.updatehealth()
Гитхаб так отображает, чуть ниже такой же кусочек но не удалённый.

2024-08-07 13:49 UTC, Helg2 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	var/datum/internal_organ/heart/heart = new
Скилл ишуй

2024-08-07 15:00 UTC, homexp13 commented on code/modules/mob/living/carbon/human/human_status_procs.dm
> -	if(isspeciessynthetic(src))
мог бы и не переносить

2024-08-07 15:01 UTC, homexp13 commented on code/modules/mob/living/carbon/life.dm
> +				if(ishuman(src))
проверку убрать

2024-08-07 15:01 UTC, homexp13 commented on code/modules/mob/living/living.dm
> -/mob/living/proc/vomit()
блять а где и как?

2024-08-07 15:04 UTC, homexp13 commented on code/modules/predator/yautja/chems.dm
> +/datum/reagent/thwei/on_mob_life(mob/living/carbon/human/L, metabolism)
он моб лайф можно везде до карбона сократить

2024-08-07 15:06 UTC, homexp13 commented on code/modules/mob/living/living.dm
> -/mob/living/proc/vomit()
а в карбона убрал ладно

2024-08-07 15:07 UTC, homexp13 commented on code/modules/mob/living/carbon/life.dm
> +				if(ishuman(src))
опционально

2024-08-07 17:34 UTC, Helg2 commented on code/modules/mob/living/carbon/human/human_status_procs.dm
> -	if(isspeciessynthetic(src))
Тупняк

2024-08-09 18:24 UTC, Tatarla approved these changes

2024-08-09 18:24 UTC, merged