Новые турели #17
PMC-Unga-Marines/RuTGMC-Reborn pull request #97
Opened 2024-08-21 16:22 UTC by homexp13

## `Основные изменения`

фидовские турки

## `Как это улучшит игру`

Много красивых турелей, более разнообразные механики. Турели больше не продаются в коробках. Турели больше нельзя настакивать около друг-друга. Инженеры всегда получают бесплатную турель.

## `Ченджлог`

```
:cl: fe-ed
add: Добавил новые турели.
del: Удалил старые турели и коробки.
balance: Инженеры получают 1 бесплатную турель.
soundadd: Новое звуковое сопровождение у турелей.
imageadd: Полный респрайт всех турелей/их магазинов.
/:cl:
```

2024-08-21 16:23 UTC, homexp13 commented
всё должно впринципе работать, фид просто конфликты не решил

2024-08-21 16:41 UTC, Helg2 commented on code/modules/projectiles/guns/sentries.dm
> +	desc = "Набор инструментов, используемый для улучшения базовой модели турелей. При использовании возврату не подлежит."
Не совсем понятна фраза про возврату не подлежит

2024-08-21 17:03 UTC, Helg2 requested changes
Рассортируй .dmi турелей, ато это организационный пиздец

2024-08-21 17:03 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +	soundloop = new(list(src))
```suggestion
	soundloop = new(list(src), active)
```
Сужу по примерам в коде если честно

2024-08-21 17:11 UTC, Helg2 reviewed
Я не подписывался быть редактором xd

2024-08-21 17:11 UTC, Helg2 commented on code/modules/reqs/supplypacks.dm
> +	name = "Набор улучшения турели TUR-B"
```suggestion
	name = "Набор для улучшения турели TUR-B"
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +		span_notice("Вы подняли [src] на место."))
```suggestion
		span_notice("Вы поставили [src] на место."))
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +	to_chat(user, span_notice("Вы перестали использовать [src], автоматика ИИ возобновлает работу."))
```suggestion
	to_chat(user, span_notice("Вы прекратили использовать [src], автоматика ИИ возобновляет работу."))
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +	to_chat(user, span_notice("Вы отключили ИИ у [src] для ручного управления."))
```suggestion
	to_chat(user, span_notice("Вы отключили ИИ [src] для перехода на ручное управление."))
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +			visible_message(span_warning("Красный светодиод у [src] ярко мигает!"))
```suggestion
			visible_message(span_warning("Красный светодиод на [src] ярко мигает!"))
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +				span_warning("Вы [safe ? "включ" : "отключ"]или предокранитель у [src]</span>"))
```suggestion
				span_warning("Вы [safe ? "включ" : "отключ"]или предохранитель у [src]</span>"))
```

2024-08-21 17:11 UTC, Helg2 commented on code/modules/projectiles/sentries.dm
> +				span_notice("Вы [alert ? "включ" : "отключ"]или систему опопвещений у [src]."))
```suggestion
				span_notice("Вы [alert ? "включ" : "отключ"]или систему оповещений [src]."))
```

2024-08-21 17:11 UTC, homexp13 commented on code/modules/projectiles/guns/sentries.dm
> +	qdel(src)
![image](https://github.com/user-attachments/assets/c5aec0e9-6dfe-441c-9479-bf2f8dc4d152)
фид по примеру наверно делал, просто src лишний вписал

2024-08-21 17:12 UTC, homexp13 commented on code/modules/projectiles/guns/sentries.dm
> +	if(!do_after(user, 7.7 SECONDS, NONE, src, BUSY_ICON_ENERGY, prog_bar = null))
фид момент

2024-08-21 17:23 UTC, homexp13 commented on code/modules/projectiles/sentries.dm
> +				span_warning("Вы [safe ? "включ" : "отключ"]или предокранитель у [src]</span>"))
=)

2024-08-22 06:40 UTC, homexp13 commented
перенёс патроны в ammo.dmi, иконки выбора турели в radial.dmi

2024-08-22 14:20 UTC, Helg2 approved these changes
Ну вроде норм

2024-08-22 14:21 UTC, merged

2024-08-24 21:03 UTC, Bemchina commented
Вот бы турель дополнительную можно было купить очков за 30±(25 на улучшение турелей(50 на 2, так у инженера 5 поинтов останется на очки и 3 сишки)